$wallpaper = /home/patrick/.config/wallpapers/abstract.jpg

$background = rgb(1d1011)
$foreground = rgb(f7dcde)

$color0 = rgb(170b0c)
$color1 = rgb(ffb2ba)
$color2 = rgb(ffb2ba)
$color3 = rgb(ffb691)
$color4 = rgb(b91c47)
$color5 = rgb(7c2a39)
$color6 = rgb(a04400)
$color7 = rgb(e1bec1)
$color8 = rgb(a9898c)
$color9 = rgb(ffb2ba)
$color10 = rgb(ffb2ba)
$color11 = rgb(ffb691)
$color12 = rgb(b91c47)
$color13 = rgb(7c2a39)
$color14 = rgb(a04400)
$color15 = rgb(f7dcde)
