$wallpaper = /home/mkhmtcore/.config/wallpapers/general-girl-red.jpg

$background = rgb(1c110d)
$foreground = rgb(f5ddd7)

$color0 = rgb(160b08)
$color1 = rgb(ffb59e)
$color2 = rgb(ffb59e)
$color3 = rgb(e3c54d)
$color4 = rgb(ed673b)
$color5 = rgb(703624)
$color6 = rgb(c6a933)
$color7 = rgb(e0bfb6)
$color8 = rgb(a78a82)
$color9 = rgb(ffb59e)
$color10 = rgb(ffb59e)
$color11 = rgb(e3c54d)
$color12 = rgb(ed673b)
$color13 = rgb(703624)
$color14 = rgb(c6a933)
$color15 = rgb(f5ddd7)
