$wallpaper = /home/mkhmtcore/.config/wallpapers/foggy-green.png

$background = rgb(121410)
$foreground = rgb(e3e3dc)

$color0 = rgb(0d0f0b)
$color1 = rgb(add193)
$color2 = rgb(bccbae)
$color3 = rgb(8ad4c4)
$color4 = rgb(476633)
$color5 = rgb(3e4b34)
$color6 = rgb(15695c)
$color7 = rgb(c3c8ba)
$color8 = rgb(8d9286)
$color9 = rgb(add193)
$color10 = rgb(bccbae)
$color11 = rgb(8ad4c4)
$color12 = rgb(476633)
$color13 = rgb(3e4b34)
$color14 = rgb(15695c)
$color15 = rgb(e3e3dc)
